// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_task_kata/test/presentaion/views/task_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:bloc/bloc.dart' as _i7;
import 'package:flutter_task_kata/domain/usecases/add_task.dart' as _i2;
import 'package:flutter_task_kata/domain/usecases/get_tasks.dart' as _i3;
import 'package:flutter_task_kata/domain/usecases/toggle_task.dart' as _i4;
import 'package:flutter_task_kata/presentation/cubit/task_cubit.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAddTask_0 extends _i1.SmartFake implements _i2.AddTask {
  _FakeAddTask_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTasks_1 extends _i1.SmartFake implements _i3.GetTasks {
  _FakeGetTasks_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeToggleTask_2 extends _i1.SmartFake implements _i4.ToggleTask {
  _FakeToggleTask_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTaskState_3 extends _i1.SmartFake implements _i5.TaskState {
  _FakeTaskState_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TaskCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskCubit extends _i1.Mock implements _i5.TaskCubit {
  @override
  _i2.AddTask get addTask =>
      (super.noSuchMethod(
            Invocation.getter(#addTask),
            returnValue: _FakeAddTask_0(this, Invocation.getter(#addTask)),
            returnValueForMissingStub: _FakeAddTask_0(
              this,
              Invocation.getter(#addTask),
            ),
          )
          as _i2.AddTask);

  @override
  _i3.GetTasks get getTasks =>
      (super.noSuchMethod(
            Invocation.getter(#getTasks),
            returnValue: _FakeGetTasks_1(this, Invocation.getter(#getTasks)),
            returnValueForMissingStub: _FakeGetTasks_1(
              this,
              Invocation.getter(#getTasks),
            ),
          )
          as _i3.GetTasks);

  @override
  _i4.ToggleTask get toggleTask =>
      (super.noSuchMethod(
            Invocation.getter(#toggleTask),
            returnValue: _FakeToggleTask_2(
              this,
              Invocation.getter(#toggleTask),
            ),
            returnValueForMissingStub: _FakeToggleTask_2(
              this,
              Invocation.getter(#toggleTask),
            ),
          )
          as _i4.ToggleTask);

  @override
  _i5.TaskState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeTaskState_3(this, Invocation.getter(#state)),
            returnValueForMissingStub: _FakeTaskState_3(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i5.TaskState);

  @override
  _i6.Stream<_i5.TaskState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i5.TaskState>.empty(),
            returnValueForMissingStub: _i6.Stream<_i5.TaskState>.empty(),
          )
          as _i6.Stream<_i5.TaskState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i6.Future<void> addTaskAction(String? title) =>
      (super.noSuchMethod(
            Invocation.method(#addTaskAction, [title]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> loadTasks() =>
      (super.noSuchMethod(
            Invocation.method(#loadTasks, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> toggleTaskAction(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#toggleTaskAction, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void emit(_i5.TaskState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i7.Change<_i5.TaskState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
