// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_task_kata/test/presentation/views/task_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:bloc/bloc.dart' as _i4;
import 'package:flutter_task_kata/presentation/cubit/task_cubit.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTaskState_0 extends _i1.SmartFake implements _i2.TaskState {
  _FakeTaskState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TaskCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskCubit extends _i1.Mock implements _i2.TaskCubit {
  @override
  _i2.TaskState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeTaskState_0(this, Invocation.getter(#state)),
            returnValueForMissingStub: _FakeTaskState_0(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i2.TaskState);

  @override
  _i3.Stream<_i2.TaskState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i3.Stream<_i2.TaskState>.empty(),
            returnValueForMissingStub: _i3.Stream<_i2.TaskState>.empty(),
          )
          as _i3.Stream<_i2.TaskState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.Future<void> addTaskAction(String? title) =>
      (super.noSuchMethod(
            Invocation.method(#addTaskAction, [title]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> loadTasks() =>
      (super.noSuchMethod(
            Invocation.method(#loadTasks, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> toggleTaskAction(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#toggleTaskAction, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void emit(_i2.TaskState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i4.Change<_i2.TaskState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
