// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_task_kata/test/presentaion/cubit/task_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_task_kata/domain/entities/task.dart' as _i3;
import 'package:flutter_task_kata/domain/repositories/task_repository.dart'
    as _i2;
import 'package:flutter_task_kata/domain/usecases/add_task.dart' as _i4;
import 'package:flutter_task_kata/domain/usecases/get_tasks.dart' as _i6;
import 'package:flutter_task_kata/domain/usecases/toggle_task.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTaskRepository_0 extends _i1.SmartFake
    implements _i2.TaskRepository {
  _FakeTaskRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTask_1 extends _i1.SmartFake implements _i3.Task {
  _FakeTask_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AddTask].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddTask extends _i1.Mock implements _i4.AddTask {
  MockAddTask() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TaskRepository get repo =>
      (super.noSuchMethod(
            Invocation.getter(#repo),
            returnValue: _FakeTaskRepository_0(this, Invocation.getter(#repo)),
          )
          as _i2.TaskRepository);

  @override
  _i5.Future<_i3.Task> call(String? title) =>
      (super.noSuchMethod(
            Invocation.method(#call, [title]),
            returnValue: _i5.Future<_i3.Task>.value(
              _FakeTask_1(this, Invocation.method(#call, [title])),
            ),
          )
          as _i5.Future<_i3.Task>);
}

/// A class which mocks [GetTasks].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTasks extends _i1.Mock implements _i6.GetTasks {
  MockGetTasks() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TaskRepository get repo =>
      (super.noSuchMethod(
            Invocation.getter(#repo),
            returnValue: _FakeTaskRepository_0(this, Invocation.getter(#repo)),
          )
          as _i2.TaskRepository);

  @override
  _i5.Future<List<_i3.Task>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i5.Future<List<_i3.Task>>.value(<_i3.Task>[]),
          )
          as _i5.Future<List<_i3.Task>>);
}

/// A class which mocks [ToggleTask].
///
/// See the documentation for Mockito's code generation for more information.
class MockToggleTask extends _i1.Mock implements _i7.ToggleTask {
  MockToggleTask() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TaskRepository get repo =>
      (super.noSuchMethod(
            Invocation.getter(#repo),
            returnValue: _FakeTaskRepository_0(this, Invocation.getter(#repo)),
          )
          as _i2.TaskRepository);

  @override
  _i5.Future<void> call(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
